# Generated by Django 5.0.7 on 2024-08-03 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=45)),
                (
                    "request_time",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 8, 3, 10, 20, 26, 484343)
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
