# Generated by Django 5.0.7 on 2024-08-03 15:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("api", "0001_initial"),
        ("api", "0002_apikeys_alter_requestlog_request_time_and_more"),
        ("api", "0003_alter_apikeys_valid_from_alter_requestlog_api_key_and_more"),
        ("api", "0004_alter_apikeys_valid_from_alter_requestlog_api_key_and_more"),
        ("api", "0005_alter_apikeys_valid_from_and_more"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiKeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=100, unique=True)),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 8, 3, 9, 16, 46, 890268, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("valid_to", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=45)),
                (
                    "request_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 8, 3, 9, 16, 46, 891245, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.apikeys",
                        to_field="api_key",
                    ),
                ),
            ],
        ),
    ]
