# Generated by Django 5.0.7 on 2024-08-03 08:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiKeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_key", models.CharField(max_length=100, unique=True)),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 8, 3, 10, 30, 20, 858211)
                    ),
                ),
                ("valid_to", models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name="requestlog",
            name="request_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 3, 10, 30, 20, 859210)
            ),
        ),
        migrations.AlterField(
            model_name="requestlog",
            name="api_key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="api.apikeys"
            ),
        ),
    ]
