# Generated by Django 5.0.7 on 2024-08-03 09:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_apikeys_alter_requestlog_request_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikeys",
            name="valid_from",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 3, 11, 9, 19, 894585)
            ),
        ),
        migrations.AlterField(
            model_name="requestlog",
            name="api_key",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.apikeys",
                to_field="api_key",
            ),
        ),
        migrations.AlterField(
            model_name="requestlog",
            name="request_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 3, 11, 9, 19, 895224)
            ),
        ),
    ]
